### ISSUE TITLE
Function getsubscriptionhandles not correctly finding processes from passed proctype

### ISSUE THREAD

**Issue by ThomasSmyth** [AquaQAnalytics/TorQ#212]
## Details

Related to #211, the function `.sub.getsubscriptionhandles` in `code/common/subscriptions.q` exhibits unexpected behaviour. According to the [docs](http://aquaqanalytics.github.io/TorQ/utilities/#subscriptionsq) the following should return all processes of type tickerplant but it actually returns all connections:
```
q).sub.getsubscriptionhandles[`tickerplant;`;()!()]
procname     proctype    w
--------------------------
tickerplant1 tickerplant 7
discovery1   discovery   6
gateway1     gateway     8
```

Correct behaviour is seen with `()`:
```
.sub.getsubscriptionhandles[`tickerplant;();()!()]
procname     proctype    w
--------------------------
tickerplant1 tickerplant 7
```

Behaviour of this functions needs updated so that only processes matching the current proctype are returned.

## Tasks:
- [x] Update to have null sym return all procnames matching the current proctype
- [x] Identify if `()` case should be kept; potentially this is being used in production code
- [ ] Update documentation to reflect changes
